/* =========================================================================
   BOSS-E 🎯 — Données (beta v2)
   Matières > Chapitres (dossiers) > PDF + Fiches + Quiz
   ========================================================================= */

const SUBJECTS = {
  cpp: {
    id: "cpp", name: "C++", icon: "💻", tagline: "Langage & algorithmique",
    gradient: "linear-gradient(135deg, #00599C 0%, #003B66 100%)",
    accent: "#00599C", accentSoft: "#E1EEF7",
    chapters: [
      { id: "cpp-ch1", title: "Variables, types & opérateurs", chapter: "Ch. 1", tag: "PDF", days: "2 semaines", pct: 92,
        pdf: { name: "cours-cpp-chapitre1.pdf", url: "https://yunes.informatique.univ-paris-diderot.fr/wp-content/uploads/cours/ENSAE/poly_c.pdf", content: "Chapitre 1 — Variables, types & opérateurs\n\nUne variable est un espace mémoire nommé qui stocke une valeur. En C++, chaque variable possède un type : int, double, char, bool, string…\n\nint age = 17;\ndouble pi = 3.14159;\nchar lettre = 'A';\nbool ok = true;\n\nLes opérateurs : + - * / % (arithmétiques), == != < > <= >= (comparaison), && || ! (logiques)." },
        fiches: [
          { id: "cpp-f1", title: "Les types de base", content: "**int** : entier\n**double** : décimal\n**char** : caractère\n**bool** : vrai/faux\n**string** : texte (bibliothèque <string>)" },
          { id: "cpp-f2", title: "Opérateurs à retenir", content: "**%** : reste de la division\n**&&** : ET logique\n**||** : OU logique\n**!** : négation" },
        ] },
      { id: "cpp-ch2", title: "Boucles & conditions", chapter: "Ch. 2", tag: "PDF", days: "5 jours", pct: 71,
        pdf: { name: "cours-cpp-chapitre2.pdf", content: "Chapitre 2 — Boucles & conditions\n\nif (condition) { … } else { … }\n\nfor (int i = 0; i < 10; i++) { … }\nwhile (condition) { … }\ndo { … } while (condition);" },
        fiches: [
          { id: "cpp-f3", title: "Boucles en un coup d'œil", content: "**for** : nombre d'itérations connu\n**while** : tant que la condition est vraie\n**do-while** : s'exécute au moins une fois" },
        ] },
      { id: "cpp-ch3", title: "Les pointeurs & références", chapter: "Ch. 3", tag: "À réviser", days: "3 jours", pct: 34,
        pdf: { name: "cours-cpp-chapitre3.pdf", url: "http://lipm-bioinfo.toulouse.inrae.fr/download/c_plus_plus/cours-1-12b.pdf", content: "Chapitre 3 — Pointeurs & références\n\nint x = 10;\nint* p = &x;   // p contient l'adresse de x\n*p = 20;       // déréférencement : modifie x\n\nUne référence est un alias : int& r = x;" },
        fiches: [
          { id: "cpp-f4", title: "Pointeur vs référence", content: "**Pointeur** (int*) : stocke une adresse, peut être nul, se réalloue.\n**Référence** (int&) : alias non nul, ne peut pas changer de cible." },
        ] },
      { id: "cpp-ch4", title: "Programmation orientée objet", chapter: "Ch. 4", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-cpp-chapitre4.pdf", url: "https://www.lamsade.dauphine.fr/~manouvri/C++/Cours_C++_MM.pdf", content: "Chapitre 4 — POO\n\nclass Voiture {\npublic:\n  void demarrer();\nprivate:\n  int vitesse;\n};\n\nEncapsulation : public / private. Héritage : class B : public A { … };" },
        fiches: [
          { id: "cpp-f5", title: "Encapsulation", content: "**public** : accessible de partout\n**private** : accessible uniquement dans la classe" },
        ] },
      { id: "cpp-ch5", title: "Templates & STL", chapter: "Ch. 5", tag: "PDF", days: "1 semaine", pct: 58,
        pdf: { name: "cours-cpp-chapitre5.pdf", content: "Chapitre 5 — Templates & STL\n\ntemplate <typename T> T max(T a, T b) { return a > b ? a : b; }\n\nLa STL fournit : vector, map, set, algorithm (sort, find)…" },
        fiches: [
          { id: "cpp-f6", title: "Conteneurs STL", content: "**vector** : tableau dynamique\n**map** : clé → valeur\n**set** : éléments uniques triés" },
        ] },
      { id: "cpp-ch6", title: "Gestion mémoire & RAII", chapter: "Ch. 6", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-cpp-chapitre6.pdf", content: "Chapitre 6 — Gestion mémoire & RAII\n\nint* p = new int(5);  // allocation\n…\ndelete p;             // libération\n\nRAII : la ressource est acquise dans le constructeur et libérée dans le destructeur." },
        fiches: [
          { id: "cpp-f7", title: "RAII en bref", content: "Acquisition de ressource = initialisation d'objet.\nLibération automatique quand l'objet sort de sa portée." },
        ] },
    ],
    radar: { axes: ["Syntaxe", "Pointeurs", "STL", "POO", "Mémoire", "Algo"],
      series: { "Premier essai": [55,30,40,35,25,50], "Deuxième essai": [70,45,60,50,40,65], "Réel": [85,55,70,60,55,75], "Globale": [78,50,65,55,48,70], "Globale réel": [82,62,72,66,58,78] } },
    pie: [ { label: "Yes", value: 62, style: "solid" }, { label: "Yes (en bleu)", value: 24, style: "hatched" }, { label: "À revoir", value: 14, style: "muted" } ],
    bars: { "Ch.1": 92, "Ch.2": 71, "Ch.3": 34, "Ch.4": 0, "Ch.5": 58, "Ch.6": 0 },
  },

  arduino: {
    id: "arduino", name: "Commandes Arduino", icon: "🔌", tagline: "Électronique & prototypage",
    gradient: "linear-gradient(135deg, #00979D 0%, #00666B 100%)",
    accent: "#00979D", accentSoft: "#D9F0F1",
    chapters: [
      { id: "ard-ch1", title: "Bases : setup() & loop()", chapter: "Ch. 1", tag: "PDF", days: "2 semaines", pct: 88,
        pdf: { name: "cours-arduino-chapitre1.pdf", content: "Chapitre 1 — Structure d'un programme Arduino\n\nvoid setup() { /* exécuté une fois */ }\nvoid loop() { /* exécuté en boucle */ }" },
        fiches: [ { id: "ard-f1", title: "La structure", content: "**setup()** : initialisation (une fois)\n**loop()** : boucle infinie" } ] },
      { id: "ard-ch2", title: "Entrées / sorties digitales", chapter: "Ch. 2", tag: "À réviser", days: "4 jours", pct: 66,
        pdf: { name: "cours-arduino-chapitre2.pdf", content: "Chapitre 2 — Entrées / sorties digitales\n\npinMode(13, OUTPUT);\ndigitalWrite(13, HIGH);   // allume\ndigitalRead(2);           // lit une entrée" },
        fiches: [ { id: "ard-f2", title: "Les fonctions clés", content: "**pinMode(pin, INPUT/OUTPUT)**\n**digitalWrite(pin, HIGH/LOW)**\n**digitalRead(pin)**" } ] },
      { id: "ard-ch3", title: "PWM & analogique", chapter: "Ch. 3", tag: "PDF", days: "1 semaine", pct: 52,
        pdf: { name: "cours-arduino-chapitre3.pdf", content: "Chapitre 3 — PWM & analogique\n\nanalogWrite(pin, valeur); // 0 à 255 (PWM)\nanalogRead(A0);          // 0 à 1023" },
        fiches: [ { id: "ard-f3", title: "PWM vs analogique", content: "**analogWrite** : sortie PWM 0-255\n**analogRead** : lecture 0-1023" } ] },
      { id: "ard-ch4", title: "Communication série", chapter: "Ch. 4", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-arduino-chapitre4.pdf", content: "Chapitre 4 — Communication série\n\nSerial.begin(9600);\nSerial.print(\"valeur : \");\nSerial.println(x);" },
        fiches: [ { id: "ard-f4", title: "Série", content: "**Serial.begin(bauds)** : init\n**Serial.print/println** : écrire" } ] },
    ],
    radar: { axes: ["Numérique", "Analogique", "PWM", "Série", "Capteurs", "Moteurs"],
      series: { "Premier essai": [60,40,35,45,30,25], "Deuxième essai": [75,55,50,60,45,35], "Réel": [88,60,55,70,55,40], "Globale": [80,58,52,65,50,38], "Globale réel": [86,64,58,72,58,44] } },
    pie: [ { label: "Yes", value: 55, style: "solid" }, { label: "Yes (en bleu)", value: 30, style: "hatched" }, { label: "À revoir", value: 15, style: "muted" } ],
    bars: { "Ch.1": 88, "Ch.2": 66, "Ch.3": 52, "Ch.4": 0 },
  },

  anglais: {
    id: "anglais", name: "Anglais", icon: "🇬🇧", tagline: "Niveaux B2 → C2",
    gradient: "linear-gradient(135deg, #012169 0%, #000D33 100%)",
    accent: "#012169", accentSoft: "#E1E5EE",
    chapters: [
      { id: "ang-b2a", title: "Conditionals (B2)", chapter: "B2", tag: "PDF", days: "1 semaine", pct: 84,
        pdf: { name: "cours-anglais-b2-conditionals.pdf", content: "B2 — Conditionals\n\nZero : if + present, present\nFirst : if + present, will + base\nSecond : if + past, would + base\nThird : if + past perfect, would have + pp" },
        fiches: [ { id: "ang-f1", title: "Les 4 conditionnels", content: "**0** : vérité générale\n**1er** : possible\n**2e** : hypothétique\n**3e** : passé impossible" } ] },
      { id: "ang-c1a", title: "Phrasal verbs avancés (C1)", chapter: "C1", tag: "À réviser", days: "3 jours", pct: 61,
        pdf: { name: "cours-anglais-c1-phrasal-verbs.pdf", content: "C1 — Phrasal verbs\n\nput off : reporter\nput away : ranger\nlook into : examiner\ncut down on : réduire" },
        fiches: [ { id: "ang-f2", title: "Phrasal verbs courants", content: "**put off** = reporter\n**look into** = examiner\n**cut down on** = réduire" } ] },
      { id: "ang-c2a", title: "Rédaction académique (C2)", chapter: "C2", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-anglais-c2-academic.pdf", content: "C2 — Rédaction académique\n\nStructure : introduction, développement, conclusion.\nConnecteurs : however, furthermore, in contrast, consequently." },
        fiches: [ { id: "ang-f3", title: "Connecteurs logiques", content: "**Addition** : furthermore, moreover\n**Contraste** : however, in contrast\n**Cause** : consequently, therefore" } ] },
    ],
    radar: { axes: ["Grammaire", "Vocabulaire", "Écoute", "Lecture", "Écrit", "Oral"],
      series: { "Premier essai": [65,70,50,72,55,60], "Deuxième essai": [78,80,62,80,66,70], "Réel": [88,86,74,87,78,80], "Globale": [82,84,70,84,74,76], "Globale réel": [86,87,76,88,80,82] } },
    pie: [ { label: "Yes", value: 70, style: "solid" }, { label: "Yes (en bleu)", value: 20, style: "hatched" }, { label: "À revoir", value: 10, style: "muted" } ],
    bars: { "B2": 84, "C1": 54, "C2": 0 },
  },

  espagnol: {
    id: "espagnol", name: "Espagnol", icon: "🇪🇸", tagline: "Niveaux B1 → C2",
    gradient: "linear-gradient(135deg, #AA151B 0%, #70090E 100%)",
    accent: "#AA151B", accentSoft: "#F5E1E2",
    chapters: [
      { id: "esp-b1a", title: "Ser vs Estar (B1)", chapter: "B1", tag: "PDF", days: "1 semaine", pct: 90,
        pdf: { name: "cours-espanol-b1-ser-estar.pdf", content: "B1 — Ser vs Estar\n\nSER : identité, profession, origine, heure.\nESTAR : lieu, état temporaire, humeur." },
        fiches: [ { id: "esp-f1", title: "Ser vs Estar", content: "**SER** = permanent (soy, eres, es…)\n**ESTAR** = temporaire (estoy, estás, está…)" } ] },
      { id: "esp-b2a", title: "Subjonctif présent (B2)", chapter: "B2", tag: "À réviser", days: "5 jours", pct: 57,
        pdf: { name: "cours-espanol-b2-subjuntivo.pdf", content: "B2 — Presente de subjuntivo\n\nhablo → hable, hables, hable, hablemos, habléis, hablen\ncomo → coma ; vivo → viva" },
        fiches: [ { id: "esp-f2", title: "Formation du subjonctif", content: "Partir de la 1re pers. du présent de l'indicatif, changer la voyelle : -ar → -e, -er/-ir → -a." } ] },
      { id: "esp-b1b", title: "Le passé composé (B1)", chapter: "B1", tag: "PDF", days: "1 semaine", pct: 63,
        pdf: { name: "cours-espanol-b1-preterito.pdf", content: "B1 — Pretérito perfecto\n\nhaber + participe passé : he hablado, has comido, ha vivido…" },
        fiches: [ { id: "esp-f3", title: "Passé composé", content: "**he/has/ha/hemos/habéis/han** + participe (-ado, -ido)" } ] },
      { id: "esp-c1a", title: "Expressions idiomatiques (C1)", chapter: "C1", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-espanol-c1-idiomaticas.pdf", content: "C1 — Expresiones idiomáticas\n\nEstar en las nubes (être dans la lune)\nTener buena cara (avoir bonne mine)" },
        fiches: [ { id: "esp-f4", title: "Expressions", content: "**Estar en las nubes** = être distrait\n**Tener buena cara** = avoir bonne mine" } ] },
    ],
    radar: { axes: ["Grammaire", "Conjugaison", "Vocabulaire", "Écoute", "Lecture", "Oral"],
      series: { "Premier essai": [70,55,68,60,74,62], "Deuxième essai": [80,66,76,70,82,72], "Réel": [90,78,85,80,89,82], "Globale": [86,74,82,76,86,78], "Globale réel": [90,80,86,82,90,84] } },
    pie: [ { label: "Yes", value: 66, style: "solid" }, { label: "Yes (en bleu)", value: 22, style: "hatched" }, { label: "À revoir", value: 12, style: "muted" } ],
    bars: { "B1": 77, "B2": 57, "C1": 0 },
  },

  python: {
    id: "python", name: "Python", icon: "🐍", tagline: "Programmation & data",
    gradient: "linear-gradient(135deg, #3776AB 0%, #1F4E72 100%)",
    accent: "#3776AB", accentSoft: "#E1EBF4",
    chapters: [
      { id: "py-ch1", title: "Variables & types de base", chapter: "Ch. 1", tag: "PDF", days: "2 semaines", pct: 85,
        pdf: { name: "cours-python-cite.pdf", url: "https://python.sdv.u-paris.fr/cours-python.pdf", content: "Chapitre 1 — Variables & types\n\nPython est un langage open-source, simple et lisible.\n\nage = 17      # int\npi = 3.14159   # float\nnom = \"Ada\"    # str\nok = True      # bool\n\nLa fonction type(x) donne le type d'un objet." },
        fiches: [ { id: "py-f1", title: "Les types de base", content: "**int** : entier\n**float** : décimal\n**str** : texte\n**bool** : True/False\n**list** : liste modifiable" } ] },
      { id: "py-ch2", title: "Conditions & boucles", chapter: "Ch. 2", tag: "PDF", days: "1 semaine", pct: 70,
        pdf: { name: "cours-python-saclay.pdf", url: "https://www.imo.universite-paris-saclay.fr/~filipa.caetano/python.pdf", content: "Chapitre 2 — Conditions & boucles\n\nif x > 0:\n    print(\"positif\")\nelif x < 0:\n    print(\"négatif\")\nelse:\n    print(\"nul\")\n\nfor i in range(10):\n    print(i)\n\nwhile condition:\n    ..." },
        fiches: [ { id: "py-f2", title: "Structures de contrôle", content: "**if/elif/else** : condition\n**for ... in range()** : boucle bornée\n**while** : boucle conditionnelle" } ] },
      { id: "py-ch3", title: "Listes, tuples & dictionnaires", chapter: "Ch. 3", tag: "À réviser", days: "3 jours", pct: 45,
        pdf: { name: "cours-python3-lemaire.pdf", url: "https://www.imo.universite-paris-saclay.fr/~sophie.lemaire/polyl3python.pdf", content: "Chapitre 3 — Structures de données\n\nliste = [1, 2, 3]        # modifiable\ntuple_ = (1, 2)          # immuable\ndico = {\"clé\": \"valeur\"}  # association clé → valeur\n\nliste.append(4) ; liste[0] ; dico[\"clé\"]" },
        fiches: [ { id: "py-f3", title: "Liste vs tuple", content: "**list** : modifiable [ ]\n**tuple** : immuable ( )\n**dict** : clé → valeur { }" } ] },
      { id: "py-ch4", title: "Fonctions & modules", chapter: "Ch. 4", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-python3-lemaire.pdf", url: "https://www.imo.universite-paris-saclay.fr/~sophie.lemaire/polyl3python.pdf", content: "Chapitre 4 — Fonctions & modules\n\ndef carre(x):\n    return x * x\n\nimport math\nmath.sqrt(16)\n\nfrom module import fonction" },
        fiches: [ { id: "py-f4", title: "Fonctions", content: "**def nom(params):** puis **return**\n**import** module\n**from ... import ...**" } ] },
      { id: "py-ch5", title: "NumPy & calcul scientifique", chapter: "Ch. 5", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-python-saclay.pdf", url: "https://www.imo.universite-paris-saclay.fr/~filipa.caetano/python.pdf", content: "Chapitre 5 — NumPy\n\nimport numpy as np\na = np.array([1, 2, 3])\na * 2  # opération vectorisée\n\nnp.mean(a), np.sum(a), np.dot(a, a)" },
        fiches: [ { id: "py-f5", title: "NumPy", content: "**np.array** : tableau\n**np.mean/sum/dot** : stats\n**vectorisation** : opérations sans boucle" } ] },
      { id: "py-ch6", title: "Fichiers & exceptions", chapter: "Ch. 6", tag: "PDF", days: "1 semaine", pct: 0,
        pdf: { name: "cours-python-cite.pdf", url: "https://python.sdv.u-paris.fr/cours-python.pdf", content: "Chapitre 6 — Fichiers & exceptions\n\nwith open(\"fichier.txt\") as f:\n    contenu = f.read()\n\ntry:\n    x = 1/0\nexcept ZeroDivisionError:\n    print(\"Division par zéro\")" },
        fiches: [ { id: "py-f6", title: "Fichiers & exceptions", content: "**with open() as f** : lecture sûre\n**try/except** : gérer les erreurs" } ] },
    ],
    radar: { axes: ["Syntaxe", "Boucles", "Listes", "Fonctions", "NumPy", "Fichiers"],
      series: { "Premier essai": [70, 55, 50, 45, 20, 30], "Deuxième essai": [82, 70, 65, 60, 35, 45], "Réel": [88, 78, 72, 70, 45, 55], "Globale": [85, 74, 68, 66, 40, 50], "Globale réel": [90, 80, 74, 72, 48, 58] } },
    pie: [ { label: "Maîtrisé", value: 58, style: "solid" }, { label: "Partiel", value: 26, style: "hatched" }, { label: "À revoir", value: 16, style: "muted" } ],
    bars: { "Ch.1": 85, "Ch.2": 70, "Ch.3": 45, "Ch.4": 0, "Ch.5": 0, "Ch.6": 0 },
  },

  excel: {
    id: "excel", name: "Excel", icon: "📊", tagline: "Tableur & bureautique",
    gradient: "linear-gradient(135deg, #217346 0%, #12472A 100%)",
    accent: "#217346", accentSoft: "#DDEBE1",
    chapters: [
      { id: "ex-ch1", title: "Classeur, feuilles & cellules", chapter: "Ch. 1", tag: "PDF", days: "2 semaines", pct: 90,
        pdf: { name: "cours-excel-labri.pdf", url: "https://www.labri.fr/perso/maabout/L2SE/Excel1.pdf", content: "Chapitre 1 — Le tableur Excel\n\nUn fichier Excel = un classeur.\nUn classeur contient des feuilles de calcul.\nUne feuille = un tableau de cellules (lignes × colonnes).\nUne cellule est repérée par sa référence (ex. B2)." },
        fiches: [ { id: "ex-f1", title: "Le vocabulaire", content: "**Classeur** : fichier .xlsx\n**Feuille** : grille de cellules\n**Cellule** : case (ex. A1, B2)" } ] },
      { id: "ex-ch2", title: "Formules & fonctions", chapter: "Ch. 2", tag: "PDF", days: "1 semaine", pct: 72,
        pdf: { name: "cours-excel-upec.pdf", url: "https://lacl.u-pec.fr/gava/cours/Droit/M1/cours_init_excel.pdf", content: "Chapitre 2 — Formules & fonctions\n\nUne formule commence par =.\n=SOMME(A1:A10)  → somme\n=MOYENNE(A1:A10) → moyenne\n=MAX(...) =MIN(...) =NB(...)" },
        fiches: [ { id: "ex-f2", title: "Fonctions de base", content: "**=SOMME(plage)**\n**=MOYENNE(plage)**\n**=MAX / =MIN / =NB**" } ] },
      { id: "ex-ch3", title: "Références absolues & relatives", chapter: "Ch. 3", tag: "À réviser", days: "3 jours", pct: 40,
        pdf: { name: "cours-excel-montpellier.pdf", url: "https://moodle.umontpellier.fr/pluginfile.php/2676161/course/overviewfiles/PolycopExcel.pdf?forcedownload=1", content: "Chapitre 3 — Références\n\nA1  : référence relative (s'ajuste à la copie)\n$A$1 : référence absolue (figée)\n$A1 / A$1 : références mixtes\n\nLe $ bloque la ligne ou la colonne." },
        fiches: [ { id: "ex-f3", title: "Le signe $", content: "**A1** : relative\n**$A$1** : absolue (figée)\n**$A1** : colonne figée\n**A$1** : ligne figée" } ] },
      { id: "ex-ch4", title: "SI, ET, OU, RECHERCHEV", chapter: "Ch. 4", tag: "Nouveau chapitre", days: "2 semaines", pct: 0,
        pdf: { name: "cours-excel-upec.pdf", url: "https://lacl.u-pec.fr/gava/cours/Droit/M1/cours_init_excel.pdf", content: "Chapitre 4 — Fonctions logiques\n\n=SI(condition; valeur_si_vrai; valeur_si_faux)\n=ET(cond1; cond2)\n=OU(cond1; cond2)\n=RECHERCHEV(valeur; table; colonne; FAUX)" },
        fiches: [ { id: "ex-f4", title: "Fonctions logiques", content: "**=SI(cond;vrai;faux)**\n**=ET(...) =OU(...)**\n**=RECHERCHEV(v;t;c;FAUX)**" } ] },
      { id: "ex-ch5", title: "Graphiques & tableaux croisés", chapter: "Ch. 5", tag: "PDF", days: "1 semaine", pct: 0,
        pdf: { name: "cours-excel-montpellier.pdf", url: "https://moodle.umontpellier.fr/pluginfile.php/2676161/course/overviewfiles/PolycopExcel.pdf?forcedownload=1", content: "Chapitre 5 — Graphiques & tableaux croisés\n\nSélectionner les données → Insertion → Graphique (histogramme, secteur, courbe…).\nUn tableau croisé dynamique résume de grandes bases de données." },
        fiches: [ { id: "ex-f5", title: "Graphiques", content: "**Insertion → Graphique**\nTypes : histogramme, secteur, courbe\n**Tableau croisé dynamique** : résumé de données" } ] },
    ],
    radar: { axes: ["Cellules", "Formules", "Références", "Fonctions", "Graphiques", "Base de données"],
      series: { "Premier essai": [75, 55, 40, 35, 30, 25], "Deuxième essai": [85, 70, 55, 50, 45, 35], "Réel": [90, 80, 65, 60, 55, 45], "Globale": [88, 76, 60, 56, 50, 40], "Globale réel": [92, 82, 68, 62, 58, 48] } },
    pie: [ { label: "Maîtrisé", value: 60, style: "solid" }, { label: "Partiel", value: 24, style: "hatched" }, { label: "À revoir", value: 16, style: "muted" } ],
    bars: { "Ch.1": 90, "Ch.2": 72, "Ch.3": 40, "Ch.4": 0, "Ch.5": 0 },
  },
};

const SUBJECT_IDS = Object.keys(SUBJECTS);

/* ------------------------- Banque de questions ------------------------- */
/* difficulty : facile | moyen | difficile */
const QUESTION_BANK = {
  cpp: [
    { id: "cpp-q1", difficulty: "difficile", q: "Que contient une variable de type pointeur ?",
      options: ["Une valeur entière", "L'adresse mémoire d'une autre variable", "Un tableau de caractères", "Une référence constante"], correct: 1,
      ref: { page: 42, title: "Les pointeurs en C++", chapter: "Chapitre 3", text: "Un pointeur stocke l'adresse mémoire d'une autre variable.",
        explanation: "Un pointeur mémorise l'emplacement (adresse) d'une valeur en mémoire. On le déclare avec * et on récupère l'adresse avec &.",
        pdf: "cours-cpp-chapitre3.pdf", links: [{ label: "cppreference — Pointer", url: "https://en.cppreference.com/w/cpp/language/pointer" }] } },
    { id: "cpp-q2", difficulty: "moyen", q: "Quel mot-clé alloue de la mémoire dynamiquement en C++ ?",
      options: ["malloc", "alloc", "new", "create"], correct: 2,
      ref: { page: 61, title: "Allocation dynamique", chapter: "Chapitre 3", text: "new alloue de la mémoire sur le tas.",
        explanation: "new renvoie un pointeur et initialise l'objet. On libère avec delete pour éviter les fuites mémoire.",
        pdf: "cours-cpp-chapitre3.pdf", links: [{ label: "cppreference — new", url: "https://en.cppreference.com/w/cpp/language/new" }] } },
    { id: "cpp-q3", difficulty: "difficile", q: "Qu'est-ce que le RAII ?",
      options: ["Un algorithme de tri", "Lier la durée de vie d'une ressource à celle d'un objet", "Un pointeur intelligent", "Un mot-clé d'exception"], correct: 1,
      ref: { page: 88, title: "Gestion mémoire & RAII", chapter: "Chapitre 6", text: "RAII : la ressource est liée au cycle de vie d'un objet.",
        explanation: "Acquise dans le constructeur, libérée dans le destructeur : pas de fuite, même en cas d'exception.",
        pdf: "cours-cpp-chapitre6.pdf", links: [{ label: "cppreference — RAII", url: "https://en.cppreference.com/w/cpp/language/raii" }] } },
    { id: "cpp-q4", difficulty: "facile", q: "Que fait `int& ref = x;` ?",
      options: ["Copie la valeur de x", "Crée une référence (alias) de x", "Crée un pointeur vers x", "Erreur de compilation"], correct: 1,
      ref: { page: 50, title: "Références", chapter: "Chapitre 3", text: "Une référence est un alias d'une variable existante.",
        explanation: "ref et x désignent la même mémoire : modifier ref modifie x. Une référence ne peut pas être nulle.",
        pdf: "cours-cpp-chapitre3.pdf", links: [] } },
    { id: "cpp-q5", difficulty: "moyen", q: "Quel conteneur STL est un tableau dynamique redimensionnable ?",
      options: ["std::map", "std::vector", "std::set", "std::array"], correct: 1,
      ref: { page: 95, title: "Conteneurs STL", chapter: "Chapitre 5", text: "std::vector est un tableau dynamique.",
        explanation: "vector gère sa taille automatiquement ; array a une taille fixe, map associe clé→valeur, set stocke des éléments uniques.",
        pdf: "cours-cpp-chapitre5.pdf", links: [] } },
    { id: "cpp-q6", difficulty: "facile", q: "À quoi sert un destructeur ?",
      options: ["À créer l'objet", "À libérer les ressources à la destruction", "À copier l'objet", "À surcharger un opérateur"], correct: 1,
      ref: { page: 78, title: "Constructeurs & destructeurs", chapter: "Chapitre 4", text: "Le destructeur libère les ressources.",
        explanation: "Appelé automatiquement quand l'objet sort de sa portée ; essentiel pour le RAII.",
        pdf: "cours-cpp-chapitre4.pdf", links: [] } },
    { id: "cpp-q7", difficulty: "difficile", q: "Que garantit `const` sur une méthode membre ?",
      options: ["Elle retourne un int", "Elle ne modifie pas l'objet", "Elle est statique", "Elle est inline"], correct: 1,
      ref: { page: 83, title: "Const-correctness", chapter: "Chapitre 4", text: "Une méthode const ne modifie pas l'objet.",
        explanation: "Elle peut être appelée sur un objet const ; elle garantit au compilateur qu'aucun membre n'est modifié.",
        pdf: "cours-cpp-chapitre4.pdf", links: [] } },
    { id: "cpp-q8", difficulty: "facile", q: "Quelle ligne inclut la bibliothèque d'entrée/sortie ?",
      options: ["#include <iostream>", "import iostream", "using iostream", "#include stdio"], correct: 0,
      ref: { page: 8, title: "Premier programme", chapter: "Chapitre 1", text: "#include <iostream> donne accès à cout et cin.",
        explanation: "Les directives #include insèrent le contenu d'un en-tête ; <iostream> fournit cout, cin, cerr.",
        pdf: "cours-cpp-chapitre1.pdf", links: [] } },
  ],

  arduino: [
    { id: "ard-q1", difficulty: "facile", q: "Quelle fonction s'exécute en boucle infinie ?",
      options: ["setup()", "main()", "loop()", "run()"], correct: 2,
      ref: { page: 15, title: "Structure d'un programme Arduino", chapter: "Chapitre 1", text: "loop() est appelée en boucle après setup().",
        explanation: "setup() s'exécute une seule fois ; loop() tourne indéfiniment.",
        pdf: "cours-arduino-chapitre1.pdf", links: [{ label: "Arduino — loop()", url: "https://www.arduino.cc/reference/en/language/structure/sketch/loop/" }] } },
    { id: "ard-q2", difficulty: "facile", q: "Quelle commande allume une LED sur la broche 13 ?",
      options: ["analogWrite(13, HIGH)", "digitalWrite(13, HIGH)", "pinMode(13, HIGH)", "readWrite(13, HIGH)"], correct: 1,
      ref: { page: 23, title: "Sorties digitales", chapter: "Chapitre 2", text: "digitalWrite(13, HIGH) met la broche à l'état haut.",
        explanation: "Il faut d'abord pinMode(13, OUTPUT), puis digitalWrite pour HIGH (allumée) ou LOW.",
        pdf: "cours-arduino-chapitre2.pdf", links: [{ label: "Arduino — digitalWrite()", url: "https://www.arduino.cc/reference/en/language/functions/digital-io/digitalwrite/" }] } },
    { id: "ard-q3", difficulty: "moyen", q: "Quelle est la plage de valeurs de analogRead() ?",
      options: ["0 à 255", "0 à 1023", "0 à 65535", "1 à 100"], correct: 1,
      ref: { page: 30, title: "Entrées analogiques", chapter: "Chapitre 3", text: "analogRead renvoie 0 à 1023 (10 bits).",
        explanation: "Le convertisseur analogique-numérique de l'Uno est sur 10 bits, soit 1024 niveaux.",
        pdf: "cours-arduino-chapitre3.pdf", links: [] } },
    { id: "ard-q4", difficulty: "moyen", q: "Quelle plage utilise analogWrite() pour le PWM ?",
      options: ["0 à 255", "0 à 1023", "0 à 5", "0 à 100"], correct: 0,
      ref: { page: 33, title: "PWM", chapter: "Chapitre 3", text: "analogWrite accepte 0 à 255.",
        explanation: "Le rapport cyclique est codé sur 8 bits : 0 = éteint, 255 = plein régime.",
        pdf: "cours-arduino-chapitre3.pdf", links: [] } },
    { id: "ard-q5", difficulty: "facile", q: "À quoi sert Serial.begin(9600) ?",
      options: ["À allumer la LED", "À initialiser la communication série à 9600 bauds", "À démarrer la boucle", "À lire un capteur"], correct: 1,
      ref: { page: 40, title: "Communication série", chapter: "Chapitre 4", text: "Serial.begin(9600) initialise la liaison série.",
        explanation: "Les deux côtés (Arduino et moniteur) doivent utiliser le même débit en bauds.",
        pdf: "cours-arduino-chapitre4.pdf", links: [] } },
    { id: "ard-q6", difficulty: "difficile", q: "Quel est l'avantage de millis() sur delay() ?",
      options: ["Il est plus précis", "Il ne bloque pas le programme", "Il consomme moins", "Il est plus rapide"], correct: 1,
      ref: { page: 47, title: "Gestion du temps", chapter: "Chapitre 4", text: "millis() est non bloquant, contrairement à delay().",
        explanation: "delay() gèle tout le programme ; millis() permet de faire autre chose en attendant.",
        pdf: "cours-arduino-chapitre4.pdf", links: [] } },
    { id: "ard-q7", difficulty: "difficile", q: "Que fait pinMode(2, INPUT_PULLUP) ?",
      options: ["Active une résistance de rappel interne sur la broche 2", "Sortie PWM", "Active un pull-down", "Désactive la broche"], correct: 0,
      ref: { page: 28, title: "Résistances de rappel", chapter: "Chapitre 2", text: "INPUT_PULLUP active le pull-up interne.",
        explanation: "La broche est maintenue à HIGH par défaut ; un bouton la met à LOW quand on appuie.",
        pdf: "cours-arduino-chapitre2.pdf", links: [] } },
    { id: "ard-q8", difficulty: "moyen", q: "À quoi sert la fonction map() ?",
      options: ["À créer une carte", "À convertir une valeur d'une plage vers une autre", "À trier un tableau", "À lire la mémoire"], correct: 1,
      ref: { page: 35, title: "Fonctions utiles", chapter: "Chapitre 3", text: "map(v, inMin, inMax, outMin, outMax) re-proportionne une valeur.",
        explanation: "Exemple : map(analogRead(A0), 0, 1023, 0, 255) adapte une lecture pour un PWM.",
        pdf: "cours-arduino-chapitre3.pdf", links: [] } },
  ],

  anglais: [
    { id: "ang-q1", difficulty: "moyen", q: "Complétez : « If I ___ rich, I would travel the world. »",
      options: ["am", "was", "were", "be"], correct: 2,
      ref: { page: 31, title: "Second conditional", chapter: "B2 — Conditionals", text: "Au second conditionnel, on emploie « were » pour toutes les personnes.",
        explanation: "Situation hypothétique : if + past simple, would + base verbale.",
        pdf: "cours-anglais-b2-conditionals.pdf", links: [{ label: "Cambridge — Conditionals", url: "https://dictionary.cambridge.org/grammar/british-grammar/conditionals" }] } },
    { id: "ang-q2", difficulty: "moyen", q: "Quel phrasal verb signifie « mettre de côté, ranger » ?",
      options: ["put off", "put away", "put up with", "put on"], correct: 1,
      ref: { page: 44, title: "Phrasal verbs avancés", chapter: "C1 — Vocabulary", text: "« put away » = ranger ou mettre de côté.",
        explanation: "put off = reporter · put up with = tolérer · put on = enfiler.",
        pdf: "cours-anglais-c1-phrasal-verbs.pdf", links: [] } },
    { id: "ang-q3", difficulty: "moyen", q: "Quel temps pour une action commencée dans le passé qui continue ?",
      options: ["Past simple", "Present perfect", "Future simple", "Past continuous"], correct: 1,
      ref: { page: 12, title: "Present perfect", chapter: "B2 — Grammar", text: "Le present perfect exprime un lien passé→présent.",
        explanation: "have/has + participe passé : « I have lived here for 5 years ».",
        pdf: "cours-anglais-b2-conditionals.pdf", links: [] } },
    { id: "ang-q4", difficulty: "moyen", q: "Quel pronom relatif pour une chose ?",
      options: ["who", "which", "whose", "whom"], correct: 1,
      ref: { page: 18, title: "Relative clauses", chapter: "B2 — Grammar", text: "which se rapporte à une chose.",
        explanation: "who = personne, which = chose, whose = possession.",
        pdf: "cours-anglais-b2-conditionals.pdf", links: [] } },
    { id: "ang-q5", difficulty: "difficile", q: "Complétez : « ___ the rain, we went out. »",
      options: ["Despite", "Although", "Because", "However"], correct: 0,
      ref: { page: 52, title: "Concessive clauses", chapter: "C1 — Grammar", text: "Despite + nom ; Although + proposition.",
        explanation: "Despite the rain (nom) ; Although it was raining (proposition).",
        pdf: "cours-anglais-c2-academic.pdf", links: [] } },
    { id: "ang-q6", difficulty: "difficile", q: "Transposez au discours indirect : « I am tired » → He said he ___ tired.",
      options: ["is", "was", "had been", "will be"], correct: 1,
      ref: { page: 58, title: "Reported speech", chapter: "C1 — Grammar", text: "Le présent devient passé au discours indirect.",
        explanation: "On recule d'un temps : am → was.",
        pdf: "cours-anglais-c2-academic.pdf", links: [] } },
    { id: "ang-q7", difficulty: "facile", q: "Que signifie « used to » ?",
      options: ["Une habitude passée", "Un futur proche", "Une obligation", "Une capacité"], correct: 0,
      ref: { page: 9, title: "Used to", chapter: "B2 — Grammar", text: "used to exprime une habitude passée.",
        explanation: "« I used to play tennis » = je jouais au tennis autrefois.",
        pdf: "cours-anglais-b2-conditionals.pdf", links: [] } },
    { id: "ang-q8", difficulty: "difficile", q: "Quel temps exprime une action finie avant un moment futur ?",
      options: ["Future perfect", "Future continuous", "Present perfect", "Past perfect"], correct: 0,
      ref: { page: 64, title: "Future perfect", chapter: "C1 — Grammar", text: "will have + participe passé.",
        explanation: "« By 2030, I will have graduated » = terminé avant 2030.",
        pdf: "cours-anglais-c2-academic.pdf", links: [] } },
  ],

  espagnol: [
    { id: "esp-q1", difficulty: "facile", q: "Complétez : « Ella ___ médica. » (état durable)",
      options: ["está", "es", "son", "sea"], correct: 1,
      ref: { page: 18, title: "Ser vs Estar", chapter: "B1 — Gramática", text: "ser s'utilise pour les caractéristiques permanentes.",
        explanation: "SER : profession, origine, identité. ESTAR : lieu, état temporaire.",
        pdf: "cours-espanol-b1-ser-estar.pdf", links: [{ label: "RAE — Diccionario", url: "https://dle.rae.es/" }] } },
    { id: "esp-q2", difficulty: "moyen", q: "Quelle forme est au subjonctif présent ?",
      options: ["hablo", "hable", "hablaré", "hablaba"], correct: 1,
      ref: { page: 39, title: "El presente de subjuntivo", chapter: "B2 — Subjuntivo", text: "« hable » est le subjonctif présent de hablar.",
        explanation: "Formation : hablo → hable, hables, hable, hablemos, habléis, hablen.",
        pdf: "cours-espanol-b2-subjuntivo.pdf", links: [{ label: "RAE — hablar", url: "https://dle.rae.es/hablar" }] } },
    { id: "esp-q3", difficulty: "difficile", q: "Complétez : « Ayer ___ al cine. » (action ponctuelle passée)",
      options: ["fui", "iba", "he ido", "iré"], correct: 0,
      ref: { page: 27, title: "Pretérito indefinido", chapter: "B1 — Pasados", text: "L'indefinido exprime une action passée achevée.",
        explanation: "fui = passé simple (action finie) ; iba = imparfait (description/habitude).",
        pdf: "cours-espanol-b1-preterito.pdf", links: [] } },
    { id: "esp-q4", difficulty: "moyen", q: "Complétez : « A mí me ___ el chocolate. »",
      options: ["gusto", "gusta", "gustan", "gusté"], correct: 1,
      ref: { page: 22, title: "Verbo gustar", chapter: "B1 — Gramática", text: "gustar s'accorde avec la chose aimée.",
        explanation: "Le sujet est « el chocolate » (singulier) → gusta.",
        pdf: "cours-espanol-b1-ser-estar.pdf", links: [] } },
    { id: "esp-q5", difficulty: "difficile", q: "« Voy a Madrid ___ tren. » (moyen de transport)",
      options: ["por", "para", "en", "de"], correct: 2,
      ref: { page: 45, title: "Preposiciones", chapter: "B2 — Gramática", text: "« en » pour le moyen de transport.",
        explanation: "en tren, en coche, en avión, a pie.",
        pdf: "cours-espanol-b2-subjuntivo.pdf", links: [] } },
    { id: "esp-q6", difficulty: "moyen", q: "Comment se forme le subjonctif de « comer » (yo) ?",
      options: ["como", "coma", "comía", "comeré"], correct: 1,
      ref: { page: 41, title: "Formación del subjuntivo", chapter: "B2 — Subjuntivo", text: "comer → coma.",
        explanation: "Verbes en -er/-ir : on remplace -o par -a : como → coma.",
        pdf: "cours-espanol-b2-subjuntivo.pdf", links: [] } },
    { id: "esp-q7", difficulty: "facile", q: "Complétez : « Me ___ un café, por favor. » (conditionnel poli)",
      options: ["gusta", "gustaría", "gustó", "gustaré"], correct: 1,
      ref: { page: 34, title: "El condicional", chapter: "B2 — Gramática", text: "Le conditionnel exprime la politesse.",
        explanation: "Me gustaría = j'aimerais.",
        pdf: "cours-espanol-b2-subjuntivo.pdf", links: [] } },
    { id: "esp-q8", difficulty: "moyen", q: "Complétez : « Me ___ todos los días. » (verbe pronominal)",
      options: ["lavo", "lava", "lavan", "lavamos"], correct: 0,
      ref: { page: 20, title: "Verbos reflexivos", chapter: "B1 — Gramática", text: "Les verbes pronominaux utilisent me/te/se/nos/os/se.",
        explanation: "« me lavo » = je me lave.",
        pdf: "cours-espanol-b1-ser-estar.pdf", links: [] } },
  ],

  python: [
    { id: "py-q1", difficulty: "facile", q: "Quel mot-clé définit une fonction en Python ?",
      options: ["function", "def", "func", "define"], correct: 1,
      ref: { page: 12, title: "Fonctions & modules", chapter: "Chapitre 4", text: "def nom(params): définit une fonction.",
        explanation: "def suivi du nom et des paramètres, puis deux-points et un bloc indenté. La fonction renvoie une valeur avec return.",
        pdf: "cours-python3-lemaire.pdf", links: [{ label: "Docs Python — def", url: "https://docs.python.org/fr/3/tutorial/controlflow.html#defining-functions" }] } },
    { id: "py-q2", difficulty: "facile", q: "Comment créer une liste en Python ?",
      options: ["{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)", "<1, 2, 3>"], correct: 1,
      ref: { page: 20, title: "Listes", chapter: "Chapitre 3", text: "Une liste se crée avec des crochets [ ].",
        explanation: "[ ] = liste modifiable, ( ) = tuple immuable, { } = dictionnaire ou ensemble.",
        pdf: "cours-python3-lemaire.pdf", links: [] } },
    { id: "py-q3", difficulty: "moyen", q: "Que renvoie `type(3.14)` ?",
      options: ["int", "float", "str", "double"], correct: 1,
      ref: { page: 6, title: "Types de base", chapter: "Chapitre 1", text: "type() renvoie le type d'un objet ; 3.14 est un float.",
        explanation: "En Python, les décimaux sont des float ; il n'existe pas de type double séparé.",
        pdf: "cours-python-cite.pdf", links: [] } },
    { id: "py-q4", difficulty: "difficile", q: "Quelle structure est immuable (non modifiable) ?",
      options: ["list", "dict", "tuple", "set"], correct: 2,
      ref: { page: 24, title: "Tuples", chapter: "Chapitre 3", text: "Un tuple est immuable.",
        explanation: "Un tuple ( ) ne peut pas être modifié après création, contrairement à une liste [ ].",
        pdf: "cours-python3-lemaire.pdf", links: [] } },
    { id: "py-q5", difficulty: "moyen", q: "Que fait `range(5)` ?",
      options: ["Une liste de 1 à 5", "Les entiers 0 à 4", "Une liste aléatoire", "Une erreur"], correct: 1,
      ref: { page: 15, title: "Boucles", chapter: "Chapitre 2", text: "range(5) génère 0, 1, 2, 3, 4.",
        explanation: "range démarre à 0 et s'arrête avant la borne : range(5) = 0..4.",
        pdf: "cours-python-saclay.pdf", links: [] } },
    { id: "py-q6", difficulty: "difficile", q: "Quel package pour le calcul scientifique vectorisé ?",
      options: ["math", "random", "NumPy", "datetime"], correct: 2,
      ref: { page: 40, title: "NumPy", chapter: "Chapitre 5", text: "NumPy fournit les tableaux et le calcul vectorisé.",
        explanation: "import numpy as np ; np.array permet des opérations sans boucle explicite.",
        pdf: "cours-python-saclay.pdf", links: [] } },
    { id: "py-q7", difficulty: "moyen", q: "Que fait `with open(\"f.txt\") as f:` ?",
      options: ["Ouvre un fichier qui se ferme automatiquement", "Crée un dossier", "Supprime un fichier", "Trie un fichier"], correct: 0,
      ref: { page: 50, title: "Fichiers", chapter: "Chapitre 6", text: "with garantit la fermeture automatique du fichier.",
        explanation: "Le gestionnaire de contexte ferme le fichier même en cas d'erreur.",
        pdf: "cours-python-cite.pdf", links: [] } },
    { id: "py-q8", difficulty: "facile", q: "Quel opérateur teste l'égalité ?",
      options: ["=", "==", "===", ":="], correct: 1,
      ref: { page: 8, title: "Opérateurs", chapter: "Chapitre 1", text: "== compare deux valeurs ; = est l'affectation.",
        explanation: "= assigne, == compare. Il n'y a pas de === en Python.",
        pdf: "cours-python-cite.pdf", links: [] } },
  ],

  excel: [
    { id: "ex-q1", difficulty: "facile", q: "Par quoi commence une formule Excel ?",
      options: ["@", "=", "+", "#"], correct: 1,
      ref: { page: 5, title: "Formules", chapter: "Chapitre 2", text: "Toute formule commence par le signe =.",
        explanation: "Sans =, Excel traite la saisie comme du texte, pas comme un calcul.",
        pdf: "cours-excel-labri.pdf", links: [] } },
    { id: "ex-q2", difficulty: "facile", q: "Que calcule =SOMME(A1:A5) ?",
      options: ["La moyenne", "La somme des cellules A1 à A5", "Le maximum", "Le nombre de cellules"], correct: 1,
      ref: { page: 9, title: "Fonctions", chapter: "Chapitre 2", text: "SOMME additionne la plage indiquée.",
        explanation: "MOYENNE fait la moyenne, MAX le maximum, NB compte les cellules.",
        pdf: "cours-excel-upec.pdf", links: [] } },
    { id: "ex-q3", difficulty: "moyen", q: "Que signifie la référence $A$1 ?",
      options: ["Référence relative", "Référence absolue (figée)", "Référence mixte", "Une erreur"], correct: 1,
      ref: { page: 14, title: "Références", chapter: "Chapitre 3", text: "$A$1 est une référence absolue.",
        explanation: "Le $ bloque la colonne et la ligne lors de la copie de la formule.",
        pdf: "cours-excel-montpellier.pdf", links: [] } },
    { id: "ex-q4", difficulty: "moyen", q: "Que fait =SI(B2>10; \"Oui\"; \"Non\") ?",
      options: ["Affiche Oui si B2 > 10, sinon Non", "Compte les cellules", "Recherche une valeur", "Une somme"], correct: 0,
      ref: { page: 20, title: "Fonction SI", chapter: "Chapitre 4", text: "SI renvoie une valeur selon une condition.",
        explanation: "Syntaxe : =SI(condition; valeur_si_vrai; valeur_si_faux).",
        pdf: "cours-excel-upec.pdf", links: [] } },
    { id: "ex-q5", difficulty: "difficile", q: "À quoi sert RECHERCHEV ?",
      options: ["À chercher une valeur dans une table", "À additionner", "À faire un graphique", "À trier"], correct: 0,
      ref: { page: 22, title: "RECHERCHEV", chapter: "Chapitre 4", text: "RECHERCHEV cherche une valeur dans la 1re colonne d'une table.",
        explanation: "=RECHERCHEV(valeur; table; n°colonne; FAUX) pour une correspondance exacte.",
        pdf: "cours-excel-upec.pdf", links: [] } },
    { id: "ex-q6", difficulty: "moyen", q: "Un classeur Excel est composé de…",
      options: ["Feuilles de calcul", "Diapositives", "Pages web", "Paragraphes"], correct: 0,
      ref: { page: 3, title: "Classeur", chapter: "Chapitre 1", text: "Un classeur contient une ou plusieurs feuilles.",
        explanation: "Chaque feuille est une grille de cellules (lignes × colonnes).",
        pdf: "cours-excel-labri.pdf", links: [] } },
    { id: "ex-q7", difficulty: "difficile", q: "Quel outil résume une grande base de données ?",
      options: ["Le tableau croisé dynamique", "La mise en forme", "Le correcteur", "L'en-tête"], correct: 0,
      ref: { page: 40, title: "Tableaux croisés", chapter: "Chapitre 5", text: "Le tableau croisé dynamique synthétise les données.",
        explanation: "Il permet de regrouper, compter et totaliser rapidement de grands tableaux.",
        pdf: "cours-excel-montpellier.pdf", links: [] } },
    { id: "ex-q8", difficulty: "facile", q: "Quel type de graphique pour des proportions ?",
      options: ["Secteur (camembert)", "Nuage de points", "Histogramme", "Courbe"], correct: 0,
      ref: { page: 34, title: "Graphiques", chapter: "Chapitre 5", text: "Le diagramme en secteurs représente des parts.",
        explanation: "Histogramme = comparaisons, courbe = évolution, secteur = proportions.",
        pdf: "cours-excel-montpellier.pdf", links: [] } },
  ],
};

/* Cartes de mémorisation (type Anki) */
const FLASHCARDS = {
  cpp: [
    { front: "int* p = &x;", back: "p est un pointeur qui contient l'adresse de x." },
    { front: "delete[] tab;", back: "Libère un tableau alloué avec new[]." },
    { front: "std::vector<int>", back: "Tableau dynamique redimensionnable de la STL." },
    { front: "& (référence)", back: "Alias non nul d'une variable existante." },
  ],
  arduino: [
    { front: "pinMode(pin, OUTPUT)", back: "Configure une broche en sortie." },
    { front: "analogWrite(pin, 128)", back: "PWM (0-255), ex. luminosité d'une LED." },
    { front: "Serial.begin(9600)", back: "Initialise la communication série à 9600 bauds." },
    { front: "millis()", back: "Temps écoulé en ms depuis le démarrage (non bloquant)." },
  ],
  anglais: [
    { front: "put off", back: "Reporter, remettre à plus tard." },
    { front: "look into", back: "Examiner, se pencher sur." },
    { front: "cut down on", back: "Réduire (sa consommation)." },
    { front: "take after", back: "Ressembler à (un parent)." },
  ],
  espagnol: [
    { front: "ser", back: "Caractéristique permanente (profession, origine)." },
    { front: "estar", back: "État temporaire (lieu, humeur)." },
    { front: "hable, hables, hable…", back: "Subjonctif présent de « hablar »." },
    { front: "Me gustaría", back: "« J'aimerais » (conditionnel poli)." },
  ],
  python: [
    { front: "def carre(x):\n    return x*x", back: "Définit une fonction qui renvoie le carré de x." },
    { front: "for i in range(5)", back: "Boucle sur 0, 1, 2, 3, 4." },
    { front: "liste = [1, 2, 3]", back: "Liste modifiable (contrairement au tuple)." },
    { front: "import numpy as np", back: "Importe NumPy pour le calcul scientifique." },
  ],
  excel: [
    { front: "=SOMME(A1:A10)", back: "Additionne les cellules de A1 à A10." },
    { front: "$A$1", back: "Référence absolue : figée lors de la copie." },
    { front: "=SI(cond;vrai;faux)", back: "Renvoie une valeur selon une condition." },
    { front: "=RECHERCHEV(v;t;c;FAUX)", back: "Cherche v dans la 1re colonne de t, renvoie la colonne c." },
  ],
};

/* Légende officielle du cahier des charges */
const RADAR_LEGEND = ["Premier essai", "Deuxième essai", "Réel", "Globale", "Globale réel"];
const RADAR_COLORS = { "Premier essai": "#8E8E93", "Deuxième essai": "#FF9500", "Réel": "#34C759", "Globale": "#FF2D55", "Globale réel": "#1C1C1E" };

const QUIZ_SIZES = [5, 10, 15, 20, 40, 50, 100];
const DIFFICULTIES = ["facile", "moyen", "difficile"];
